services:
  web:
    build: .
    image: php-multi-cgi-sqlite
    container_name: webapp
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/html
      # SQLite
      - ../app/data:/var/www/html/data
    restart: unless-stopped
